name: c-cpp-linter

on:
  pull_request:
    branches: [main]
    paths:
      - "**.c"
      - "**.cpp"
      - "**.h"
      - "**.hpp"
      - "**.cc"
      - "**.hh"
      - "**.cxx"
      - "**.hxx"
  workflow_call:

jobs:
  c-cpp-linter:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      pull-requests: write
    steps:
      - name: Check out the repo
        uses: actions/checkout@v4.1.0

      - name: Linting source code
        uses: cpp-linter/cpp-linter-action@v2.16.6
        id: linter
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          style: "file"
          thread-comments: "update"
          tidy-review: true
          format-review: true

      - name: Linting status check
        if: steps.linter.outputs.checks-failed > 0
        run: exit 1
